Add Iterator Design Pattern
aquaruiz/Java-Spring-Recap pull request #15
Opened 2020-07-13 10:08 UTC by aquaruiz

2020-07-13 10:08 UTC, aquaruiz commented
@qnislavnachev

2020-07-14 10:32 UTC, qnislavnachev requested changes

2020-07-14 10:32 UTC, qnislavnachev commented on design-patterns/behavioral-patterns/src/iterator/IcecreamRepository.java
> +				return currentIndex < icecreams.length && icecreams[currentIndex] != null;
You will have a problem in the implementation. if input some ice creams and one of them is 'null' the iteration will not work properly. For Example:
```
new String["vanila", null, "chocolate"]
```

With this array of ice creams the iteration will stop at the second one and the only the first one will be rendered.
You have two options here to not allow null elements in the array or to allow iteration of the null elements

2020-07-15 11:03 UTC, qnislavnachev requested changes

2020-07-15 11:03 UTC, qnislavnachev commented on design-patterns/behavioral-patterns/src/iterator/IcecreamRepository.java
> +				return currentIndex < icecreams.length && icecreams[currentIndex] != null;
The check for null is no longer necessary as we are sure that the array does not contains null elements

2020-07-15 16:38 UTC, aquaruiz commented
How can we be sure about that?

2020-07-15 17:09 UTC, merged