Add Observer Design Pattern
aquaruiz/Java-Spring-Recap pull request #17
Opened 2020-07-14 08:16 UTC by aquaruiz

2020-07-14 08:17 UTC, aquaruiz commented
@qnislavnachev

2020-07-15 11:06 UTC, qnislavnachev requested changes

2020-07-15 11:06 UTC, qnislavnachev commented on design-patterns/behavioral-patterns/src/observer/Surveillance.java
> +	protected void isolate() {
For me that method is not required.

2020-07-15 13:02 UTC, aquaruiz commented on design-patterns/behavioral-patterns/src/observer/Surveillance.java
> +	protected void isolate() {
ok

2020-07-15 17:11 UTC, merged