Add Strategy Design Pattern
aquaruiz/Java-Spring-Recap pull request #19
Opened 2020-07-14 10:11 UTC by aquaruiz

2020-07-14 10:13 UTC, aquaruiz commented
@qnislavnachev

2020-07-15 12:38 UTC, qnislavnachev requested changes

2020-07-15 12:38 UTC, qnislavnachev commented on design-patterns/behavioral-patterns/src/strategy/Strategy.java
> +    int executeStrategy(int a, int b);
execute() is enough I believe.

2020-07-15 12:38 UTC, qnislavnachev commented on design-patterns/behavioral-patterns/src/strategy/Strategy.java
> +public interface Strategy {
MathStrategy is better name for this interface I think

2020-07-15 12:38 UTC, qnislavnachev commented on design-patterns/behavioral-patterns/src/strategy/ConcreteStrategyMultiply.java
> +public class ConcreteStrategyMultiply implements Strategy {
MultiplicationStrategy will fit better as a name. Apply same naming convention for the rest strategies.

2020-07-15 17:17 UTC, merged